services:
  - type: web
    name: snapworth
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /var/data/snapworth.db
      - key: SESSION_DB_DIR
        value: /var/data

    disk:
      name: snapworth-data
      mountPath: /var/data
      sizeGB: 1
